version: '3.8'
services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5435:5432'

volumes:
  db_data:
